### PR TITLE
Fix corrupted data file bugs

### PR DESCRIPTION
**Pull request by KT27Learn**
### Description

Ensure LeadsForce still loads even with a corrupted data file or data fields.

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [X] Code quality improvements

### How to test

Attribute | Invalid Value | Result
-- | -- | --
ClientId | Alex and Bernice has same clientId (i.e. "1") | Duplicated clients identified and empty address book used
ClientId | Alex has clientId "00" | json parses successfully and Alex's id is 0
LastMet | Alex has an future LM (i.e. 25-12-2021 (08:00~09:00), Starbucks @ UTown) | empty address book used
NextMeeting | Alex has an outdated NM (i.e. 25-02-2021 (08:00~09:00), Starbucks @ UTown) | empty address book used

### Checklist

- [X] I have tested this code
- [ ] I have updated the documentation

### CODE REVIEW

**Review by benedictchuajj — APPROVED** [review]
LGTM! This solves all the issues that were brought up in #209. 

However, I encounter a small problem with the clientCounter now. Although there is no longer any issues with duplicate client ids, the current method does not allow a user to do anything if their file is corrupted. 

For example, if we delete the clientCounter value or remove it, the clientCounter in the app will be stuck at 0. The user will be unable to add any client until they remove the person with id 0, and this problem will keep persisting as their clientCounter is essentially reset and has no way to increment normally. 

One suggestion that I have to potentially solve this is to remove the dependency on getting clientCounter from the json file and instead, whenever an address book is open, we store the max client id that is read from the client list and use that to get our next clientCounter (+1 to the max)

Feel free to implement the fix differently if there's another way to solve this

**Comment by wyrchris** [comment]
> NextMeeting	Alex has an outdated NM (i.e. 25-02-2021 (08:00~09:00), Starbucks @ UTown)	empty address book used

I think this should be boot up as normal but update the next meeting to last met. Else, when the user boot up after the next meeting has elapsed, all their data will be wiped

**Comment by KT27Learn** [comment]
@benedictchuajj 
I think thats a valid suggestion. But I feel that cause of the way our client Id is implemented where client counter is forever incrementing, I think that method will not allow for example where client counter is set to be at maybe 40 from the last use but currently last client in the list has a client id of 20. Unless maybe we relook at this aspect of our app haha

**Comment by KT27Learn** [comment]
@wyrchris 
Oh alright I think that sounds q logical haha. Will work on that feature in a seperate PR

**Pull request merged**
