### PR TITLE
Limit field inputs

### PR DESCRIPTION
**Pull request by benedictchuajj**
### Description

Unsure if this counts as a valid PR for feature freeze but this resolves an issue where long inputs for client attributes breaks the GUI's functionality of displaying information.

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] Code quality improvements

### Checklist

- [X] I have tested this code
- [ ] I have updated the documentation

### CODE REVIEW

**Comment by CrownKira** [comment]
I think that `MAX_LENGTH` can be encapsulated by the `Field` interface since that's what it is used for :)

**Comment by benedictchuajj** [comment]
> I think that `MAX_LENGTH` can be encapsulated by the `Field` interface since that's what it is used for :)

Oh, that's a great suggestion! 

Is it okay if I were to encapsulate it not in `Field` but a separate interface like `FieldLength`? Think there would be too many variations of Fields otherwise because only some fields like CurrentPlan, Address, NextMeeting should have the longer limit

**Review by wyrchris — CHANGES_REQUESTED** [review]
Looks good, mostly working as expected but there is an issue with the current default sampleDataUtil. This prevents the default address book from booting up since the field's in the sample client does not match the new requirement. Apart from changing the sample client's field, will likely need to catch this issue if user decides to manually amend the json file similar to #159.

Also, separately when testing, realised that even with limit of 30 characters, if user decides to input a disposable income with 18 digits, then the value displayed will not display properly.

**Comment by benedictchuajj** [comment]
Thanks for catching these problems! Will fix it asap

**Comment by benedictchuajj** [comment]
> Apart from changing the sample client's field, will likely need to catch this issue if user decides to manually amend the json file similar to #159.

Have worked on the problems you've described besides this. Looks like this problem might be fixed in #209 so I will not touch on it for now.

@wyrchris if it's alright with you, could I request for your review again?

**Review by wyrchris — APPROVED** [review]
LGTM!

**Pull request merged**
