### PR TITLE
Final final adjustments for UGDG 🥱 😭

### PR DESCRIPTION
**Pull request by benedictchuajj**
### Description

HMU with any last minutes updates here

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### Checklist

- [ ] I have tested this code
- [ ] I have updated the documentation

### CODE REVIEW

**Comment by CrownKira** [comment]
Screenshot 2021-11-08 at 3 15 38 AM

Does anyone know how to remove this? hiddenClass thing

**Comment by CrownKira** [comment]
> Screenshot 2021-11-08 at 3 15 38 AM
> 
> Does anyone know how to remove this? hiddenOutside thing

i am done! you can merge this after this is resolved. imma go sleep now

**Comment by CrownKira** [comment]
Screenshot 2021-11-08 at 11 06 22 AM

The "User Guide" headings appear twice, should we remove it ?

**Comment by CrownKira** [comment]
Screenshot 2021-11-08 at 11 13 10 AM

Hi, does anyone know how to convert the `` to grey box?

**Comment by CrownKira** [comment]
> Screenshot 2021-11-08 at 3 15 38 AM
> 
> Does anyone know how to remove this? hiddenOutside thing

This is urgent. I would appreciate if anyone can help look into this. It is present in almost all our architecture diagrams, it is not supposed to be there.

**Comment by wyrchris** [comment]
> > Screenshot 2021-11-08 at 3 15 38 AM
> > Does anyone know how to remove this? hiddenOutside thing
> 
> This is urgent. I would appreciate if anyone can help look into this. It is present in almost all our architecture diagrams, it is not supposed to be there.

It appears to be the case that the original font color was white which was ab3 used as way to hide the text from appearing.
There does not seem to be away to manually set the font color of it as the color setting using skinparam is global

**Comment by wyrchris** [comment]
> It appears to be the case that the original font color was white which was ab3 used as way to hide the text from appearing. There does not seem to be away to manually set the font color of it as the color setting using skinparam is global

I think I found a way to do it, will try to fix it now

**Pull request merged**
