### PR TITLE
Fix corrupted field in data file bug

### PR DESCRIPTION
**Pull request by KT27Learn**
### Description

Fix previous bug where an invalid name in data file will cause whole app to crash. Currently any invalid field represented in the data file will result in the app launching with an empty addressbook.

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Code quality improvements

### How to test

Change field in data file to an invalid field. App will launch with an empty addressbook.

### Checklist

- [X] I have tested this code
- [ ] I have updated the documentation

### CODE REVIEW

**Comment by benedictchuajj** [comment]
Some invalid outputs but address-book still opens normally without any error or can't open at all.

Attribute | Invalid Value | Result
-- | -- | --
ClientId | Alex and Bernice has same clientId (i.e. "1") | Address-book parses json and both Alex and Bernice share the same id
ClientId | Alex has clientId "00" | json parses successfully and Alex's id is 00
NextMeeting | Alex has an outdated NM (i.e. 25-02-2021 (08:00~09:00), Starbucks @ UTown) | address-book fails to start (occurs for other values that causes invalid NM, refer to #198)

**Comment by benedictchuajj** [comment]
Might be worth noting that the user can also change the `clientCounter` to an invalid value (-1, 0 when there's already a client) or rename it to `clientCounter**s**`. This causes the clientCounter to no longer be accurate and the duplicate clientId issue to occur again

**Comment by KT27Learn** [comment]
Thanks for the feedback, will take this into account and rectify

**Comment by KT27Learn** [comment]
Will post another pull request with the changes

**Pull request closed without merging**
